environment:
  matrix:
    - nodejs_version: "8"
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm i debug mime-types mz resolve-path
test_script:
  - node --version
  - npm --version
  - npm run test:lint
  - npm run test:security
  - npm run test:code
build: off
